//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gui.tasks.entities.clearing;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClearingNalog", propOrder = {
    "zaglavlje",
    "stavka"
})
@XmlRootElement(name = "Clearing_nalog")
public class ClearingNalog {

    @XmlElement(required = true)
    protected ZaglavljeClearingNaloga zaglavlje;
    @XmlElement(required = true)
    protected List<StavkaClearingNaloga> stavka;

    /**
     * Gets the value of the zaglavlje property.
     * 
     * @return
     *     possible object is
     *     {@link ZaglavljeClearingNaloga }
     *     
     */
    public ZaglavljeClearingNaloga getZaglavlje() {
        return zaglavlje;
    }

    /**
     * Sets the value of the zaglavlje property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZaglavljeClearingNaloga }
     *     
     */
    public void setZaglavlje(ZaglavljeClearingNaloga value) {
        this.zaglavlje = value;
    }

    /**
     * Gets the value of the stavka property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stavka property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStavka().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StavkaClearingNaloga }
     * 
     * 
     */
    public List<StavkaClearingNaloga> getStavka() {
        if (stavka == null) {
            stavka = new ArrayList<StavkaClearingNaloga>();
        }
        return this.stavka;
    }

}
